### ISSUE TITLE
Error: Cannot find module '../node_sqlite3.node'

### ISSUE THREAD

**Issue by alecjd** [rogeriopvl/nodo#8]
### Error: Cannot find module '/usr/local/lib/node_modules/nodo/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node'

Getting the following error whenever I try `nodo` with _any_ action:

`$ nodo <any action>`
```
module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/nodo/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodo/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by rogeriopvl** [comment]
Hey @alecjd, can you give more details about your setup? OS and node version specifically.

**Comment by rogeriopvl** [comment]
Closing this due to lack of feedback.
